Repository kjh9852/Rolling, pull requests merged in 2024-07, with the labels that each got.

#2 Feat/root color추가
  src/assets/style/reset.css
Labels: Feat

#4 Feat/section component
  src/App.js
  src/components/common/Section.jsx
  src/index.js
  src/pages/LandingPage.jsx
Labels: Feat

#6 Feat/Post AddMessage Page
  package-lock.json
  src/App.jsx
  src/assets/image/arrow_down.png
  src/assets/image/arrow_top.png
  src/assets/style/reset.css
  src/components/Post/AddMessage.js
  src/components/Select/Select.js
  src/pages/AddMessagePage.jsx
Labels: Feat

#7 Chore : prettier 설정
  .prettierrc
Labels: Chore

#24 Refactor/ UserHeader 컴포넌트 리팩토링, Badge 컴포넌트 추가
  src/App.jsx
  src/assets/style/GlobalStyle.jsx
  src/components/PostDetail/MessageList.jsx
  src/components/PostDetail/PostDetail.jsx
  src/components/PostDetail/UserActionComponent.jsx
  src/components/PostDetail/UserHeader.jsx
  src/components/PostDetail/emoji.css
  src/components/common/Badge.jsx
  src/components/common/EmojiBadge.jsx
  src/index.js
  src/pages/PostDetailPage.jsx
  src/router/RootLayout.jsx
  src/router/UserLayout.jsx
  src/ui/Header.jsx
  src/util/api.js
  src/util/backgroundColor.js
  src/util/relation.js
Labels: Feat, Refactor

#26 Refactor/LandingDetail 컴포넌트 분리
  src/App.jsx
  src/components/LandingPage/Card.jsx
  src/components/LandingPage/IntroSection.jsx
  src/components/LandingPage/LandingDetail.jsx
  src/components/LandingPage/LandingSection.jsx
  src/components/LandingPage/PointBox.jsx
  src/components/LandingPage/StartButton.jsx
  src/components/LandingPage/SubTitle.jsx
  src/components/LandingPage/Title.jsx
Labels: Refactor

#32 Style/scrollbar디자인수정
  package-lock.json
  package.json
  src/assets/image/cardImg1.png
  src/assets/image/mobileCardImg1.png
  src/assets/image/mobileCardImg2.png
  src/assets/style/GlobalStyle.jsx
  src/components/LandingPage/Card.jsx
  src/components/LandingPage/Cards.jsx
  src/components/LandingPage/DesktopLandingDetail.jsx
  src/components/LandingPage/IntroSection.jsx
  src/components/LandingPage/LandingDetail.jsx
  src/components/LandingPage/LandingSection.jsx
  src/components/LandingPage/MobileLandingDetail.jsx
  src/components/LandingPage/PointBox.jsx
  src/components/LandingPage/StartButton.jsx
  src/components/LandingPage/SubTitle.jsx
  src/components/LandingPage/TabletLandingDetail.jsx
  src/components/LandingPage/Title.jsx
Labels: Design

#28 Feat/addmessage post api구현
  src/App.jsx
  src/components/Post/AddMessage.jsx
  src/components/ProfileImageList/ProfileImageList.jsx
  src/util/api.js
Labels: Feat, Design

#30 Style/drop shadow스타일추가
  src/components/PostDetail/MessageList.jsx
  src/components/PostDetail/UserActionComponent.jsx
  src/components/PostDetail/UserHeader.jsx
  src/pages/PostDetailPage.jsx
  src/ui/Modal.jsx
Labels: Design

#33 Feat/ Modal Close 버튼 추가
  src/components/common/PrimaryButton.jsx
  src/pages/MessageDetailPage.jsx
  src/ui/Modal.jsx
Labels: Feat

#34 Feat/AddPostPage 체크되지 않은 탭 데이터 비활성화, TextInput 변경, 생성하기 동작 구현
  src/components/PostPage/AddPost.jsx
  src/components/PostPage/BgSelector.jsx
  src/components/PostPage/NameInput.jsx
  src/components/PostPage/SubmitButton.jsx
  src/components/PostPage/TextInput.jsx
  src/util/api.js
Labels: Feat

#36 Feat/contentArea/reactquillCss사용
  src/assets/style/customQuill.css
  src/components/PostDetail/MessageList.jsx
  src/components/Select/Select.jsx
Labels: Fix, Feat

#38 Feat/NotFound페이지작업
  src/App.jsx
  src/components/Post/AddMessage.jsx
  src/components/PostPage/NotFoundPage.jsx
  src/util/api.js
Labels: Feat

#40 Feat/ Edit 페이지 기능 구현
  package-lock.json
  public/index.html
  src/App.jsx
  src/assets/image/deleted.png
  src/assets/style/GlobalStyle.jsx
  src/components/Post/AddMessage.jsx
  src/components/PostDetail/MessageContainer.jsx
  src/components/PostDetail/MessageList.jsx
  src/components/PostDetail/PostDetail.jsx
  src/components/PostDetail/UserActionComponent.jsx
  src/components/PostDetail/UserHeader.jsx
  src/pages/PostEditPage.jsx
  src/util/api.js
Labels: Feat

#46 Feat/ 공유 하기 기능 추가
  .gitignore
  src/assets/image/close.png
  src/assets/image/completed.png
  src/components/PostDetail/MessageList.jsx
  src/components/PostDetail/UserActionComponent.jsx
  src/ui/Toast.jsx
  src/util/api.js
Labels: Feat

#50 Feat/add message이전버튼
  src/components/Post/AddMessage.jsx
  src/components/TextArea/ContentArea.jsx
Labels: Feat

#54 Design : react-quill스타일추가
  src/assets/style/customQuill.css
Labels: Design

#57 Refector/api데이터객체화
  src/components/Post/AddMessage.jsx
  src/util/api.js
Labels: Refactor

#58 Refactor/ AddPost 리팩토링 작업
  src/components/PostPage/AddPost.jsx
Labels: Refactor

#59 Refctor/AddMessage페이지리펙토링
  src/components/Post/AddMessage.jsx
Labels: Refactor
